on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '42 10 * * 6'

name: ci
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Build
      run: go build
    - name: Test
      run: go test

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Configure Go Environment
      run: |
        echo ::set-env name=GOPATH::${{ runner.workspace }}
        echo ::add-path::${{ runner.workspace }}/bin
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Bootstrap
      run: make bootstrap
    - name: Lint
      run: make lint
